services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=/app/dev.db
    ports:
      - 29898:3000
    volumes:
      - dev.db:/app/dev.db
      - prod.db:/app/prod.db
