services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      args:
      - DATABASE_URL=file:/app/expenses.db
    environment:
    - DATABASE_URL=file:/app/expenses.db
    ports:
    - 29898:3000
    volumes:
    - ./data/expenses.db:/app/app.db
