services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    environment:
      - DATABASE_URL=file:/app/app.db
    ports:
      - 29898:3000
    volumes:
      - /home/gustavo/expenses.db:/app/app.db
